### PR TITLE
Changed Readme design

### PR DESCRIPTION
**Pull request by sebastianlorenzo88**

### CODE REVIEW

**Comment by artem-fedorov** [comment]
Hi, I think that you include in this PR the same that in #56 except https://github.com/Blazemeter/jmeter-bzm-plugins/pull/59/commits/c62cddc625413f920baca7d208209d31f813d321 
Please, make pull from BlazeMeter:master to you Abstracta:master for cleanup commits list.
Also please fix travis build

**Comment by artem-fedorov** [comment]
@sebastianlorenzo88 
It is error from `HTTP2SamplerTest.jmx` 
```
va.util.concurrent.ExecutionException: java.lang.IllegalStateException: No Client ALPNProcessors!
	at org.eclipse.jetty.util.FuturePromise.get(FuturePromise.java:138)
	at com.blazemeter.jmeter.http2.sampler.HTTP2Connection.connect(HTTP2Connection.java:68)
	at com.blazemeter.jmeter.http2.sampler.HTTP2Request.setConnection(HTTP2Request.java:278)
	at com.blazemeter.jmeter.http2.sampler.HTTP2Request.sample(HTTP2Request.java:138)
	at com.blazemeter.jmeter.http2.sampler.HTTP2Request.sample(HTTP2Request.java:115)
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:490)
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:416)
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:250)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: No Client ALPNProcessors!
	at org.eclipse.jetty.alpn.client.ALPNClientConnectionFactory.<init>(ALPNClientConnectionFactory.java:57)
	at org.eclipse.jetty.http2.client.HTTP2Client.lambda$doStart$1(HTTP2Client.java:155)
	at org.eclipse.jetty.http2.client.HTTP2Client$ClientSelectorManager.newConnection(HTTP2Client.java:438)
	at org.eclipse.jetty.io.ManagedSelector.createEndPoint(ManagedSelector.java:222)
	at org.eclipse.jetty.io.ManagedSelector.access$1500(ManagedSelector.java:60)
	at org.eclipse.jetty.io.ManagedSelector$CreateEndPoint.run(ManagedSelector.java:825)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:754)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:672)
	... 1 more
	Suppressed: java.lang.NoClassDefFoundError: org/eclipse/jetty/alpn/ALPN
		at org.eclipse.jetty.alpn.java.client.OpenJDK8ClientALPNProcessor.init(OpenJDK8ClientALPNProcessor.java:42)
		at org.eclipse.jetty.alpn.client.ALPNClientConnectionFactory.<init>(ALPNClientConnectionFactory.java:77)
```

**Comment by artem-fedorov** [comment]
@sebastianlorenzo88  I removed
```
 - "sh ./http2/target/jmeter-test/testJMeter.sh 4.0 $HOME/.jmeter"
  - "sh ./http2/target/jmeter-test/testJMeter.sh 3.3 $HOME/.jmeter"
  - "sh ./http2/target/jmeter-test/testJMeter.sh 3.2 $HOME/.jmeter"
  - "sh ./http2/target/jmeter-test/testJMeter.sh 3.1 $HOME/.jmeter"
```
from Travis script. Could you please fix error above and rewrite your test using junit?

**Comment by sebastianlorenzo88** [comment]
Right now these tests are using BZ Taurus and their goals are to validate that the plugin works on the different version of JMeter. If we change this to use JUnit we probably execute the same script from java. Is there any particular reason that you prefer using JUnit?   

We are working on fixing this tests

**Comment by artem-fedorov** [comment]
@sebastianlorenzo88 
Please, look at https://groups.google.com/forum/?hl=ru#!topic/jmeter-plugins/L-egQ10xwEY

**Comment by artem-fedorov** [comment]
@sebastianlorenzo88 
Regarding JUnit tests it will be great to have the same JUnit test, that use JMeter 2.13 in dependencies

**Pull request closed without merging**
