### PR TITLE
Import 3 plugins

### PR DESCRIPTION
**Pull request by pablobarcelo**
HLS plugin:

- Fixed pom.xml
- Delete commented code
- Code formatted

### CODE REVIEW

**Comment by undera** [comment]
Can you do pull from origin branch and then push again? This will make unit tests to go right way.

**Comment by pablobarcelo** [comment]
Hey Andrey, 
just to check do you mean make the pull request from the master branch?

**Comment by undera** [comment]
I already merged master into `import-3-plugins`, just do pull from it

**Comment by pablobarcelo** [comment]
Ok. Thanks Andrey!

**Comment by undera** [comment]
I'll merge it, let's have baseline on that

**Comment by pablobarcelo** [comment]
Hi Andrey, 

I have a question regarding the Plugin Manager, is there any possibility to automate all the configuration required for the HTTP/2 plugin? I mean add the following steps in the Plugin Manager:

1-Download alpn-boot according to your JVM version https://www.eclipse.org/jetty/documentation/9.4.x/alpn-chapter.html

2- On Windows at the start of jmeter.bat add the next line: set JVM_ARGS= -Xbootclasspath/p:<path.to.jar>;

On Linux and Mac at the start of jmeter.sh add the next line: JVM_ARGS="-Xbootclasspath/p:<path.to.jar>"

So the user doesn't need to do anything manually.

**Comment by undera** [comment]
Hi,

It can be automated using InstallerClass, but I would not recommend
that. The problem is that you can't be sure where launching script is.

What I would recommend to do is to investigate the way to make alpn
optional for the plugin. As far as I know, alpn is needed for automatic
negotiation of connection properties. So if you force connection
properties to be HTTP/2, there's no need in alpn auto-detecting.

**Comment by pablobarcelo** [comment]
Andrey, we will be investigating the way to make APLN optional, but for the moment, as the plugin is already published, could you please add this set up to the Plugin Manager?

**Comment by undera** [comment]
It's something that you can develop yourself. See for example https://github.com/undera/jmeter-plugins/blob/master/tools/cmd/src/main/java/kg/apc/cmdtools/CMDInstaller.java

**Comment by pablobarcelo** [comment]
While we develop this installation class, could you please add this set up to the Plugin Manager? So, if anyone wants to install the plugin right now, he or she could use it. 

1-Download alpn-boot according to your JVM version https://www.eclipse.org/jetty/documentation/9.4.x/alpn-chapter.html

2- On Windows at the start of jmeter.bat add the next line: set JVM_ARGS= -Xbootclasspath/p:<path.to.jar>;

On Linux and Mac at the start of jmeter.sh add the next line: JVM_ARGS="-Xbootclasspath/p:<path.to.jar>"

Also, I can't see the documentation of HTTP/2 plugin and HLS in the Plugin Manager, the following error is displayed in the log of JMeter:

java.lang.NullPointerException: null
	at org.jmeterplugins.repository.PluginsList.getDescriptionHTML(PluginsList.java:135) ~[jmeter-plugins-manager-0.11.jar:?]
	at org.jmeterplugins.repository.PluginsList.valueChanged(PluginsList.java:95) ~[jmeter-plugins-manager-0.11.jar:?]
	at javax.swing.JList.fireSelectionValueChanged(Unknown Source) ~[?:1.8.0_121]
	at javax.swing.JList$ListSelectionHandler.valueChanged(Unknown Source) ~[?:1.8.0_121]
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source) ~[?:1.8.0_121]
	at javax.swing.DefaultListSelectionModel.fireValueChanged(Unknown Source) ~[?:1.8.0_121]
	at javax.swing.DefaultListSelectionModel.setValueIsAdjusting(Unknown Source) ~[?:1.8.0_121]
	at javax.swing.JList.setValueIsAdjusting(Unknown Source) ~[?:1.8.0_121]

**Comment by undera** [comment]
I see no installer class created by you, nothing to add into plugin descriptor. If you expect me to write that class - sorry, wrong expectation.

**Comment by pablobarcelo** [comment]
Andrey, that was not what I was expecting. I will develop the installer class and I will let you know when it's ready. I only ask if you could update the documentation of HTTP/2 plugin adding these initial steps meanwhile. In case any user wants to download the plugin. Attached is the documentation updated with these steps.

Also, I downloaded the Plugin Manager but I couldn't access to the documentation of HTTP2 and HLS plugins.

If you should need anything from us, just let me know.

[HTTP2 Plugin.docx](https://github.com/Blazemeter/jmeter-bzm-plugins/files/1200522/HTTP2.Plugin.docx)

**Comment by undera** [comment]
Documentation should also be updated by you, just create PR with changes into *.md files

**Pull request merged**
