### PR TITLE
fix labels

### PR DESCRIPTION
**Pull request by artem-fedorov**

### CODE REVIEW

**Comment by undera** [comment]
The proper way of setting component's default title is overriding `getStaticLabel()`. Doesn't it work?

**Comment by artem-fedorov** [comment]
In JMeter 3.2 was added new DefaultTreeNodeNamingPolicy:  If node does not have name after creation then name will be set Simple Class Name (org.apache.jmeter.gui.action.impl.DefaultTreeNodeNamingPolicy#nameOnCreation)

**Comment by undera** [comment]
But getStaticLabel still works as regular way, right? Like in all other plugins...

**Comment by artem-fedorov** [comment]
Are you sure, that getStaticLabel() early used for set TestElement.NAME?  Now I see, that getStaticLabel is used in drop down lists and at the top of component gui.. and JMeter doesn't set TestElement.Name from getStaticLabel()

**Pull request merged**
