### PR TITLE
Create Multi-tab Recording

### PR DESCRIPTION
**Pull request by jaydeepborkar**
Add a new feature to record multi-tab user sessions along with single tab sessions which can be used for load testing.

### CODE REVIEW

**Comment by artem-fedorov** [comment]
Hi @jaydeepborkar 
Do you mean [Chrome Extension plugin](https://chrome.google.com/webstore/detail/blazemeter-the-continuous/mbopgmdnpcbohhpnfglgohlbhfongabi?hl=en)?

**Comment by jaydeepborkar** [comment]
> Hi @jaydeepborkar
> Do you mean [Chrome Extension plugin](https://chrome.google.com/webstore/detail/blazemeter-the-continuous/mbopgmdnpcbohhpnfglgohlbhfongabi?hl=en)?

yes, chrome extension plugin :)

**Comment by artem-fedorov** [comment]
@MintLucky  FYI

**Comment by MintLucky** [comment]
Chrome extension supports multi-tab recording (for HTTP traffic and Selenium) since version 4.1.0.

**Pull request closed without merging**
