### PR TITLE
Import 3 plugins

### PR DESCRIPTION
**Pull request by pablobarcelo**
- Fix README.md
- Remove shaded jar
- Remove libs that were not used in pom.xml
- Extend and inherit code of JMeter instead of copying it.
- Unit tests for HTTP2 Sampler.

### CODE REVIEW

**Comment by undera** [comment]
Is this complete or in progress?
I'd suggest removing code instead of commenting it out.

**Comment by pablobarcelo** [comment]
It's in progress. We cover the unit test of HTTP2 Sampler. Now we are working on the coverage of the new View Result Tree.  Sure, we will remove all commented code.

**Comment by undera** [comment]
Ok, then let me know once it's ready for review

**Comment by pablobarcelo** [comment]
Andrey, we have finished the unit test of HTTP2 Plugin. 

Please let me know if there is any problem.

**Comment by undera** [comment]
All is good

**Pull request merged**
